# API proxying
[[redirects]]
  from = "/api/*"
  to = "https://embermap-dashboard-backend.herokuapp.com/api/:splat"
  status = 200

# SPA push state routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
